
#         General Settings         #

# If you start a raid, and stop shooting for 'x minutes or hours' then,
# the defending faction will receive a shield.
explosion-threshold: 15 minutes

# This is how long the shield will last after a faction
# has successfully defended a raid.
shield-duration: 15 minutes

# Prevent the placement of the following blocks during raid defense.
prevent-placement:
- TNT
- OBSIDIAN
- COBBLESTONE

# Prevent the destruction of the following blocks during raid defense.
prevent-break:
- MOB_SPAWNER

# Prevent the use of the following items during raid defense.
# Note: Here you should place the item type of your genbuckets.
prevent-use:
- MONSTER_EGG

# Prevent the use of certain commands (by the defenders) during raid.
# Here we disable three faction commands. "f" auto includes "factions" as well
prevent-commands:
- f chest
- f pv
- f vault

#         Gui Settings         #

raid-list-gui: '&8Raid List'
raid-gui: '&8Raid Gui'

#         General Messages         #

cannot-break: '&eYou cannot break this block while being raided.'
cannot-place: '&eYou cannot place this in your claims while being raided.'
cannot-use: '&eYou cannot use this item while being raided.'
cannot-execute: '&eYou cannot execute this command while being raided.'
cannot-disband: '&eYou cannot disband your faction while a raid is active.'
cannot-leave: '&eYou cannot leave your faction while a raid is active.'
cannot-command: '&eYou can not use this command while being raided.'
cannot-unclaim: '&eYou cannot unclaim land while being raided.'
shield: '&7You have a faction shield for: &a%time%'

#         Raid Start          #

raid-start-title: ''
raid-start-subtitle: '&cYour faction has initiated a raid, go fight!'
raid-start:
- ''
- '&cYou have initiated a raid on: &7%faction% (%online% Online)'
- ''
- '&cYou may type &7/raid&c for additional information.'
- ''


#         Raid Defense         #

raid-defense-title: ''
raid-defense-subtitle: '&cYou are being raided, go defend your base!'
raid-defense:
- ''
- '&cYou are being raided by: &7%faction% (%online% Online)'
- ''
- '&cYou may type &7/raid&c for additional information.'
- ''

#         Items          #

raid-item:
  name: '&c&lYOU ARE CURRENTLY IN A RAID'
  lore:
    - '&8%date%'
    - ''
    - '&8&lRAIDING: &f%attacker% &a(%onlineAttackers% Online)'
    - '&8&lDEFENDING: &f%defender% &a(%onlineDefenders% Online)'
    - ''
    - '&7The faction actively raiding must fire TNT '
    - '&7once every 15 minutes to remain in raid.'
    - ''
    - '&7While this raid is active, the defending faction'
    - '&7will be unable to mine spawners or regen walls.'
    - ''
    - '&cLast Explosion: %time% ago'